//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public long Bid { get; set; }
        public string BNumber { get; set; }
    }
}
