//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<long> TotalCreditHours { get; set; }
        public string CourseCode { get; set; }
        public Nullable<long> TheoryCreditHours { get; set; }
        public Nullable<long> LabCreditHours { get; set; }
        public Nullable<long> ProgrammeId { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public Nullable<long> Did { get; set; }
    }
}
