//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamBranch
    {
        public int ExamBranchId { get; set; }
        public string ExamBranchName { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Campus { get; set; }
        public Nullable<int> UserId { get; set; }
        public string EmpId { get; set; }
        public string Branch { get; set; }
        public string Designation { get; set; }
    }
}
