//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPWeb.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NUMLAutomatedTranscriptEntities : DbContext
    {
        public NUMLAutomatedTranscriptEntities()
            : base("name=NUMLAutomatedTranscriptEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminStaff> AdminStaffs { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Campus> Campuses { get; set; }
        public virtual DbSet<Coordinator> Coordinators { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Endpoint> Endpoints { get; set; }
        public virtual DbSet<Enroll> Enrolls { get; set; }
        public virtual DbSet<ExamBranch> ExamBranches { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Programme> Programmes { get; set; }
        public virtual DbSet<RepeatedCours> RepeatedCourses { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Scheme> Schemes { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsCours> StudentsCourses { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
