//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionId { get; set; }
        public string PermissionAllowed { get; set; }
        public int EndpointId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Endpoint Endpoint { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
