//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public int SemesterId { get; set; }
        public int StudentId { get; set; }
        public int ProgrammeId { get; set; }
    
        public virtual Programme Programme { get; set; }
        public virtual Student Student { get; set; }
    }
}
