//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.RepeatedCourses = new HashSet<RepeatedCours>();
            this.Semesters = new HashSet<Semester>();
        }
    
        public int StudentId { get; set; }
        public string SystemID { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public int RollNumber { get; set; }
        public string Department { get; set; }
        public string DegreeStatus { get; set; }
        public int CurrentSemester { get; set; }
        public string RegistrationNumber { get; set; }
        public System.DateTime DegreeStartDate { get; set; }
        public decimal CGPA { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Batch { get; set; }
        public string Faculty { get; set; }
        public string Degree { get; set; }
        public Nullable<int> CampusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepeatedCours> RepeatedCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Semester> Semesters { get; set; }
        public virtual User User { get; set; }
    }
}
