//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsCours
    {
        public int CourseId { get; set; }
        public int StudentCourseId { get; set; }
        public Nullable<long> SemesterNo { get; set; }
        public Nullable<long> Pid { get; set; }
        public string Scheme { get; set; }
    }
}
